In [1]:
import numpy as np
from PIL import Image
from scipy.stats import ortho_group
from BitVector import BitVector
msg=BitVector(intVal = 1, size = 3)
k=3
x = ortho_group.rvs(k)

In [2]:
im = Image.open(r"C:/Users/Ashahar/Desktop/Python Assignment University/FAU__MMSEC_EXERCISE/ucid_images/ucid00007.tif")
image = np.array(im)
#print (image)

In [3]:
img=image
message=7
msg=BitVector(intVal = message, size = 3)
m=[int(x) for x in msg]
print(m)
sign=[1 if i==1 else -1 for i in m]
alfa=1


print(sign)


for i in range(img.shape[0]):
    k=0
    for j in range(img.shape[2]):
        img[i][j]=img[i][j]+(alfa*sign[k]*x[k])
        k+=1

#print(img)

[1, 1, 1]
[1, 1, 1]


In [4]:
new_im = Image.fromarray(img)
new_im.save("watermarked_img07.png")

In [5]:
im_o = image
image_water = Image.open(r"watermarked_img07.png")
im_w = np.array(image_water)

In [6]:
im11= np.where(img==im_w)

In [7]:
message=(im_o-im_w)

In [8]:
message_im = Image.fromarray(message)
message_im.save("watermarked_MESSAGE.png")

In [9]:
im11

(array([  0,   0,   0, ..., 383, 383, 383], dtype=int64),
 array([  0,   0,   0, ..., 511, 511, 511], dtype=int64),
 array([0, 1, 2, ..., 0, 1, 2], dtype=int64))

In [10]:
from scipy.stats import pearsonr
corr, _ = pearsonr(im_o, im_w)

TypeError: No loop matching the specified signature and casting was found for ufunc add